apiVersion: v1
kind: Pod
metadata:
  name: demo-ruby-app
  labels:
    app: demo-ruby-app
spec:
  containers:
    - name: app-container
      image: cr.yandex/crp7r0r719t2qkhkume1/hello-ruby:0.0.1
      ports:
        - containerPort: 9292
      env:
        - name: RACK_ENV
          value: "production"
      command: ["bundle", "exec", "rackup"]
      args: ["--host", "0.0.0.0", "--port", "3000"]